default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  user: docker
  password: docker

development:
  <<: *default
  database: app_dev

test:
  <<: *default
  database: app_test
